In [2]:
import numpy as np

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [4]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [6]:
#concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])