In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

Arrays

In [4]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
f = np.array([1.2, 1.3, 1.4])
f.dtype

dtype('float64')

In [7]:
b = np.array([1, 'abc', True])
b.dtype

dtype('<U11')

In [8]:
a[0]

1

In [9]:
a[0] = 10
a

array([10,  2,  3,  4])

In [10]:
a[0] = 11.9
a

array([11,  2,  3,  4])

In [11]:
a.ndim

1

In [12]:
a.shape

(4,)

In [13]:
a.size

4

In [17]:
a = np.array([[11, 12, 13], [21, 22, 23]])
a

array([[11, 12, 13],
       [21, 22, 23]])

In [19]:
a.shape

(2, 3)

In [24]:
a[0,2]

13

In [25]:
#row
a[1,]

array([21, 22, 23])

In [26]:
#row ver.2
a[1, :]

array([21, 22, 23])

In [27]:
#column
a[:, 2]

array([13, 23])

In [29]:
a[:, 0: 2]

array([[11, 12],
       [21, 22]])

In [31]:
a[0, 1 :]

array([12, 13])

In [33]:
#Alternative options to create array
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
a = np.ones((2,3,5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [35]:
a = np.full((2,3), 7)
a

array([[7, 7, 7],
       [7, 7, 7]])

In [36]:
np.full_like(a, 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [37]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [ ]:
#Operations with arrays 
#Universal functions (ufunc)


In [40]:
a = np.ones((4))
a

array([1., 1., 1., 1.])

In [41]:
b = np.full_like(a, 2)
b

array([2., 2., 2., 2.])

In [42]:
np.add(a, b)

array([3., 3., 3., 3.])

In [43]:
a + b

array([3., 3., 3., 3.])

In [44]:
a - b

array([-1., -1., -1., -1.])

In [45]:
a * b

array([2., 2., 2., 2.])

In [46]:
a / b

array([0.5, 0.5, 0.5, 0.5])

In [47]:
c = np.zeros((1,3))
np.cos(c)

array([[1., 1., 1.]])

In [ ]:
#Vecttorization


In [50]:
a_list = [i for i in range(100000)]
type(a_list)

list

In [51]:
a_arr = np.array(a_list)
type(a_arr)

numpy.ndarray

In [53]:
#Broadcasting
a = np.array([1, 1, 1])
a + 1

array([2, 2, 2])

In [ ]:
#Arrrays are mutable!!!!


In [54]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [55]:
b[1] = 11
b

array([ 1, 11,  3])

In [56]:
a

array([ 1, 11,  3])

In [57]:
b = a.copy()
b[1] = 111
b

array([  1, 111,   3])

In [58]:
a

array([ 1, 11,  3])